FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src


COPY ["QuizUpLearn.API/QuizUpLearn.API.csproj", "QuizUpLearn.API/"]
COPY ["BusinessLogic/BusinessLogic.csproj", "BusinessLogic/"]
COPY ["Repository/Repository.csproj", "Repository/"]
RUN dotnet restore "QuizUpLearn.API/QuizUpLearn.API.csproj"

COPY . .

WORKDIR "/src/QuizUpLearn.API"
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "QuizUpLearn.API.dll"]