FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["QuizUpLearn/QuizUpLearn.API/QuizUpLearn.API.csproj", "QuizUpLearn.API/"]
COPY ["QuizUpLearn/BusinessLogic/BusinessLogic.csproj", "BusinessLogic/"]
COPY ["QuizUpLearn/Repository/Repository.csproj", "Repository/"]
RUN dotnet restore "QuizUpLearn.API/QuizUpLearn.API.csproj"

COPY QuizUpLearn/ .

WORKDIR "/src/QuizUpLearn.API"
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:10000
EXPOSE 10000
ENTRYPOINT ["dotnet", "QuizUpLearn.API.dll"]